### ISSUE TITLE
Clarification on Limitations

### ISSUE THREAD

**Issue by neurosnap** [rtsao/csjs-extractify#3]
Basically, the main limitation for extracting CSJS into its own file requires that the CSJS be within its own file, is that correct?

I couldn't have a random CSJS variable within one of my React components and have this plugin extract the CSS?

**Comment by rtsao** [comment]
Yes, the assumption is that all CSJS exists is exported as its own module. However, it would be fairly straightforward to change this plugin to allow the CSJS to exist within other files/modules as long as it was exported along with the other stuff. The basic idea of this plugin is that at build-time, it simply requires all your CSJS modules then concats all the CSS together. The reason I have the assumption that all CSJS exists as its own module is otherwise there'd be a lot of brittle convention needed to get it working (e.g. what about if I want to export multiple CSJS modules in the same file, etc). Restricting it to single `.csjs.js` files with single module exports keeps things simple.

<hr>

I've been working on a server-rendering solution that doesn't require any browserify/webpack tooling:
https://github.com/rtsao/csjs-styletron which is powered by https://github.com/rtsao/styletron.

With `csjs-styletron`, all CSS is automatically injected into the page (like `csjs-inject`, but with buffering and caching so it's a bit better), but you can also extract the CSS afterwards if rendering on the server. Then when you send down the HTML, you can send down all the rendered CSS.

For folks doing server-rendering, there's some advantages with using `csjs-styletron` over this plugin:
- Styles don't have to be known at build-time, only render-time (this allow for dynamic styles that depend on props, for example)
- CSJS doesn't have to be exported as a module. As long as `csjs` function is called at some point during the render, it works
- Automatic injection of styles into `<head>` on the client
- Extraction of rendered CSJS on the server to be sent down with rendered HTML
- No build-time process is involved at all so it works completely independently of browserify/webpack/etc.

In theory, if your CSJS is essentially "static" (or more precisely, consistent at build-time, which would need to be the case to use `csjs-extractify`)  you could use `csjs-styletron` and a small script using  `styletron` to pull out the static CSS yielding similar results as `csjs-injectify`. This would allow you to not have to explicitly export your CSJS as a module. (In fact, I might premake a script to do this, actually, since this seems like it could be a reasonably common use case. This could probably even be a browserify plugin like this one)

<hr>

`styletron` is a very generic tool. It powers this, for example: https://github.com/rtsao/react-stylematic

**Comment by derhuerst** [comment]
There's lots of useful information in the issue. Unfortunately, I (and I think many others) don't browse the issues when quickly figuring out what a module is about.

> The basic idea of this plugin is that at build-time, it simply requires all your CSJS modules then concats all the CSS together. The reason I have the assumption that all CSJS exists as its own module is otherwise there'd be a lot of brittle convention needed to get it working (e.g. what about if I want to export multiple CSJS modules in the same file, etc). Restricting it to single `.csjs.js` files with single module exports keeps things simple.

Please put exactly this in the readme! (: Also, you might link to `styletron`.

BTW great module!

**Comment by gersomvg** [comment]
@rtsao I love CSJS and actually use it in multiple productions now. Right now I use csjs-injectify, but for production it would be better to extract the css into a different bundle. ~~Csjs-injectify is also somewhat buggy, because after inspection of my bundle.js, I found out that all CSS is written out double in the source~~ (edit: this has nothing to do with csjs-injectify). My CSJS files currently depend on config files that I prefer to write in ES6 syntax, so I need to run csjs-extractify in the context of the babel transform.

What's the status on this project? The readme says:

> More sophisticated extraction is being worked on, but this should cover many use cases for now.

I would like to volunteer to make this thing happen :) I don't have any experience writing browserify plugins, but you can always give feedback or even trash it. I want to achieve the following goals:
- Run extractify in the context of browserify transforms
- Remove all occurences of the CSS from bundle.js and only store the calculated result of the class names (or does extractify already do this?)

**Comment by rtsao** [comment]
Getting everything working at build-time is a difficult problem because CSJS is just JavaScript and thus we can't just use static analysis - we need to actually _evaluate_ JavaScript.

But from within this transform, we only have access to untranspiled source code of dependent modules, which may not run in your environment.

I've learned a lot more about browserify/babel/webpack (especially since initially working on csjs-extractify) so I feel more up to the challenge of a building a better build-time solution.

I think something like this would work:
1. Create a csjs webpack loader or babel plugin that instruments each .csjs.js file with the filename, and changes the .csjs.js file so that the in addition to exporting the result of the csjs template literal, it also modifies some global variable to contain the result and filename.
2. Create a simple webpack plugin that uses string-to-module on the entire compiled bundled output to get everything in memory. Then it can extract out all the csjs results from the global variable (along with their filenames) and then replace the contents of those files with just the object results.

(I think the above should be possible with browserify as well, but I'm guessing doing this with webpack might be easier)

I probably won't have time to fully implement a better build-time solution in the near-term but I'll probably at least explore the above solution to verify it will be possible. But if you wanted to try giving it a shot I'd be happy to help out and/or provide guidance/feedback. 😄 

I haven't had time to work build-time solutions as I've been more focused on server-rendering/run-time things (which is easier to do robustly).

**Comment by gersomvg** [comment]
> Getting everything working at build-time is a difficult problem because CSJS is just JavaScript and thus we can't just use static analysis - we need to actually evaluate JavaScript.

I was already suspecting something like this, but couldn't grasp the exact scope of the problem. I will just keep using csjs-injectify at the moment. It's maybe better for me to not start with this as my first Browserify plugin.

And I agree that server-rendering is better, but there is currently no NodeJS implementation on the server of the project I'm working on. I don't think I could manage to give that priority anytime soon.

But I' m wondering; what's your opinion on using csjs-injectify in a production webapp (single-page)? I mean; stylesheet extraction also isn't possible with other inline CSS libraries that are way more popular than csjs (like Radium).
